# api_token it is sha256 digest from stock-predictor-service

media_service_api_token: 63071cfea6be52aadcd12e4170499a339eb5f481f2fa99b6d265ec335581ef77
client_service_api_token: 63071cfea6be52aadcd12e4170499a339eb5f481f2fa99b6d265ec335581ef77

auth_service_prefix: http://localhost:8080
media_service_prefix: http://localhost:8083


storage_config:
  host: localhost
  port: 5436
  user: postgres
  password: scp
  db_name: postgres
  ssl_mode: disable

swagger_config:
  user: swagger
  password: scp