# api_token it is sha256 digest from stock-predictor-service

media_service_hash_salt: 63071cfea6be52aadcd12e4170499a339eb5f481f2fa99b6d265ec335581ef77
media_service_api_token: 63071cfea6be52aadcd12e4170499a339eb5f481f2fa99b6d265ec335581ef77

auth_service_prefix: http://localhost:8080

storage_config:
  host: localhost
  port: 5438
  user: postgres
  password: scp
  db_name: postgres
  ssl_mode: disable

queue_config:
  user: rabbit
  password: scp
  host: localhost
  port: 5672
  queue_key: media_service_queue

swagger_config:
  user: swagger
  password: scp

